---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: python
  image: python:3.8-alpine
  commands:
  - python --version
  - python3 --version

- name: shell
  image: busybox
  commands:
  - pwd
  - ls -lh
  
- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 742753339946696714
    webhook_token: Bc1vaoA5uA73Ig2qyMN0va4QCvdX8Du-s4OlsnTOj25IMXQkeSd7wzebH6WVClAkJxi2

...
